default-tf-distribution: "terraform"
disable-global-apply-lock: false
emoji-reaction: "eyes"
enable-diff-markdown-format: true
enable-policy-checks: true
fail-on-pre-workflow-hook-error: false
log-level: "info"
# repo_allowlist: "github.com/gce-digital-marketing-infrastructure/INFRA-*"
use-tf-plugin-cache: false
web-basic-auth: true
repo-allowlist: "github.com/org/repo
