# Note: This file is only used for Atlantis local development
services:
  ngrok:
    image: wernight/ngrok:latest@sha256:d211f29ebcfe5f4e72df4fa8bdd9a667886e127d7fcb1be4a1af5ad83a8a1b77
    ports:
      - 4040:4040
    environment:
      # https://dashboard.ngrok.com/get-started/your-authtoken
      NGROK_AUTH: "Your auth token"
      NGROK_PROTOCOL: http
      NGROK_PORT: atlantis:4141
    depends_on:
      - atlantis
  atlantis:
    build:
      context: .
      dockerfile: Dockerfile
    command: "atlantis server --config /config.yaml"
    ports:
      - 4141:4141
    volumes:
      # - ${HOME}/.aws:/home/atlantis/.aws/:ro
      - ./config.yaml:/config.yaml
    environment:
      ATLANTIS_GH_USER: "your-github-user"
      ATLANTIS_GH_TOKEN: "your-github-token"
      ATLANTIS_GH_WEBHOOK_SECRET: "your-webhook-secret"
      # ATLANTIS_REPO_CONFIG: "/home/atlantis/atlantis.yaml" # Use ATLANTIS_REPO_CONFIG_JSON instead
      # ATLANTIS_REPO_CONFIG_JSON: '[{"id":"/.*/","branch":"/.*/","plan_requirements":["mergeable"],"apply_requirements":["approved"],"import_requirements":["approved"],"allowed_overrides":["workflow","plan_requirements"],"allow_custom_workflows":true,"policy_check":true}]'
      AWS_PROFILES: |
        [
          {
            "wmkt-gce-sandbox": "arn:aws:iam::884977855360:role/wmkt_gce_sandbox-atlantis-source-role",
            "region": "us-west-2"
          },
          {
            "wmkt-gce-prod": "arn:aws:iam::884977855360:role/atlantis-20250325181155424300000002",
            "region": "us-east-1"
          },
          {
            "terraform-state": "arn:aws:iam::884977855360:role/atlantis_state_lock",
            "region": "us-west-2"
          }
        ]

volumes:
  atlantis:
