name: Pre-Release Atlantis

on:
  release:
    types: [prereleased]

jobs:
  atlantis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a #7.0.1
      - name: Extract version tag
        id: extract_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 #4.2.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f #v4.2.0
        with:
          platforms: linux/amd64,linux/arm64
          use: true

      - name: Login to DockerHub
        uses: docker/login-action@371161bbe7024a29a25c5e19bfcbc0804fe9ad2c #4.5.2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push app
        uses: docker/build-push-action@cb941d0b895b09c17fa011d41c411b33c752cf28 #v7.3.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64 
          push: true
          tags: |
            "aliciousness/atlantis:${{ env.TAG }}"
          build-args: |
            VERSION=${{ env.TAG }}
          labels: |
            maintainer="craddock9richard@gmail.com"
            org.opencontainers.image.authors="craddock9richard@gmail.com"
